#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# Abort en cas d'entrées inattendues
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

# Enregistrement des données fournies par `acpi`
$status = $1;
$percent = $2;

# Indication de la charge
if ($status eq 'Charging' || $status eq 'Not charging'){ $full_text = '' }

# Changement du symbole de charge en fonction du niveau restant
if ($status eq 'Discharging') {

	if    ($percent < 10) { $full_text = '' }
	elsif ($percent < 38) { $full_text = '' }
	elsif ($percent < 65) { $full_text = '' }
	elsif ($percent < 88) { $full_text = '' }
	else                  { $full_text = '' }

	if ($percent < 5) { exit(33) }
}

# Affichage du pourcentage restant
$full_text .= " $percent%";

# Pour afficher le temps estimé restant
# if ($acpi =~ /(\d\d:\d\d):/) {
# 	$full_text .= " ($1)";
# }

# print text
$short_text = $full_text;
print "$full_text\n";
print "$short_text\n";

exit(0);
