#!/bin/bash

# Author : Guilain Ernotte <guilainsjc@gmail.com>

# `acpi -b` return ifo about the batteries detected.
# This grep command select the good battery (pc battery).
BAT=$(acpi -b | grep -E -o '[[:alpha:][:space:]]+, [[:digit:]]{1,3}%$')
# Extract battery status and level with some regex magic.
STATUS=$(echo "$BAT" | grep -E -o '[[:alpha:][:space:]]+')
LEVEL=$(echo "$BAT" | grep -E -o '[[:digit:]]{1,3}')

# Print status and level in a pretty formatting.
case $STATUS in
    "Not charging" | "Charging" )
        TEXT="" ;;
    "Discharging" )
        if [[ $LEVEL -le 10 ]]; then
			TEXT=""
		elif [[ $LEVEL -le 38 ]]; then
			TEXT=""
		elif [[ $LEVEL -le 65 ]]; then
			TEXT=""
		elif [[ $LEVEL -le 88 ]]; then
			TEXT=""
		else
			TEXT=""
		fi ;;
esac

echo "$TEXT$LEVEL"

# Lever le flag d'urgence (33) quand le niveau est inférieur à 5%.
[ "$LEVEL" -le 5 ] && exit 33

exit 0
