#!/bin/bash

# Ce script consiste dans un premier temps à aller extraire l'information
# renvoyée par la commande `acpi -b` concernant la batterie du pc, et dans un
# second temps à mettre en forme puis afficher cette information dans la barre
# de statut.
#
# Author : Guilain Ernotte <guilainsjc@gmail.com>

# Sélectionner la bonne batterie (celle du PC)
BAT=$(acpi -b | grep -v "rate information unavailable")

# Extraire le pourcentage de la batterie
LEVEL=$(echo $BAT | grep -Eo '[[:digit:]]{1,3}%' | grep -Eo '[[:digit:]]{1,3}')

# Cas 1 : batterie en charge ou chargée et branchée sur l'alimentation
echo $BAT | grep -Eq "Not charging|Charging" && TEXT=""

# Cas 2 : batterie en train de se décharger
echo $BAT | grep -Eq "Discharging" && \
	if [[ $LEVEL -le 10 ]]; then
		TEXT=""
	elif [[ $LEVEL -le 38 ]]; then
		TEXT=""
	elif [[ $LEVEL -le 65 ]]; then
		TEXT=""
	elif [[ $LEVEL -le 88 ]]; then
		TEXT=""
	else
		TEXT=""
	fi

# Cas 3 : l'état de la batterie est inconnu :/
echo $BAT | grep -Eqv "Not charging|Charging|Discharging" && TEXT=""

# Affichage du résultat
echo "$TEXT $LEVEL%"
