#!/bin/bash

# Author : Guilain Ernotte <guilainsjc@gmail.com>

# Ce script va simplement recueillir le temps qu'il fait ainsi que la
# température sur wttr.in. Je mets en forme l'information reçue, puis j'affiche
# le tout dans la barre de statut.

# Recueil de l'état de la météo sur wttr.in
weather=$(curl -Ss 'wttr.in?0&T&Q' | cut -c 17- | head -2)

# Aspect du temps
mood=$(echo "$weather" | head -1)
# Température (moyenne + variance)
temp=$(echo "$weather" | tail -1 | grep -Eo '\w' | head -2)
mean=$(echo "$temp" | head -1)
variance=$(echo "$temp" | tail -1)

# Choix des icônes en fonction de la météo
case $mood in
	"Sunny") icon="" ;;
	"Partly cloudy") icon="" ;;
	"Cloudy"|"Overcast") icon="" ;;
	"Light drizzle") icon="" ;;
esac	

# Affichage dans la barre de statut
echo "$icon ($mean±$variance)°C "
